# Generated by Django 2.0 on 2017-12-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20171213_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
